# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb7f1ae7cc1580cbc3da685233a9e4b35fa45a26a3a9804fb7e3aab9ecfac08dd01ec8ed52f46ca93b9aeab04c9d9db96badc8b2f22daf7cec567a0556261ca

test:
  secret_key_base: 9d5cfea1228126bd8c7acefd5a2768a96d30117178397983b84a259424f05a4790d4a3e7dbe309a236aa176d624347b53528b637ee6f3adb0999fed039fa9b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
